### ISSUE TITLE
Support cshtml

### ISSUE THREAD

**Issue by jerone** [Dany-R/IBR.StringResourceBuilder2011#4]
Any plans to support `.cshtml` files?

**Comment by Dany-R** [comment]
Hi,
no plans yet, as I do not know of that technique.
A quick query about what cshtml is told me, that it is a server-side html with C# code in it, yes?

1. Does it make use of C# resource files? This is the output of StringResourceBuilder.
2. Another question would be, whether the Visual Studio editor provides me with an object model containing the structure of the "source code"? This is the way the parsing is performed right now.

Two example projects would be very helpful for me to see the "before" and "after" state of your desired solution.
Cheers, Dany

**Comment by Dany-R** [comment]
Sorry for the unintentional closing.

**Comment by jerone** [comment]
Correctly, `.cshtml` files are HTML files with C# (or VB.NET) code. They are used by the view engine (called Razor) for ASP.NET projects.

1. Resource files can be used in any .NET project. `.cshtml` files allow C#, so references to resource keys can be added.
2. I have no idea. There is a view engine which consumes `.cshtml` files, so i guess it could be parsed. There are two places where resources can be extracted from: the normal HTML (in textnodes, or attributes) and the inline C# code (normal strings).

There are many examples on the internet and in VS templates, but I could provide some example code (taken from https://www.w3schools.com/asp/razor_syntax.asp)...

#### Before:
```cshtml
<!-- Single statement block -->
@{ var myMessage = "Hello World"; }

<!-- Inline expression or variable -->
<p>The value of myMessage is: @myMessage</p>

<!-- Multi-statement block -->
@{
  var greeting = "Welcome to our site!";
  var weekDay = DateTime.Now.DayOfWeek;
  var greetingMessage = greeting + " Here in Huston it is: " + weekDay;
}
<p>The greeting is: @greetingMessage</p> 
```

#### After:
Resource key | Value
----|------
MyMessage | `"Hello World"`
ValueOfMyMessage | `"The value of myMessage is: {0}"`
Greeting | `"Welcome to our site!"`
GreetingMessage | `"{0} Here in Huston it is: {1}"`
GreetingIs | `"The greeting is: {0}"`

```cshtml
 <!-- Single statement block -->
@{ var myMessage = Resources.MyMessage; }

<!-- Inline expression or variable -->
<p>@String.Format(Resources.ValueOfMyMessage , myMessage)</p>

<!-- Multi-statement block -->
@{
  var greeting = Resources.Greeting;
  var weekDay = DateTime.Now.DayOfWeek;
  var greetingMessage = String.Format(Resources.GreetingMessage, greeting, weekDay);
}
<p>@String.Format(Resources.GreetingIs, greetingMessage)</p>
```
