### ISSUE TITLE
VS 2013 (VS 12.0)

### ISSUE THREAD

**Issue by i18nuserz** [Dany-R/IBR.StringResourceBuilder2011#5]
I tried opening your sln in VS 2013 but get the error that the csproj cannot be loaded.  Do you still have the VS 2013 version available by chance?

**Comment by Dany-R** [comment]
Hi,
this would be V1.3.6.17 (2014-01-10). I hope it works.
Cheers, Dany

[IBR.StringResourceBuilder2011_bak17_Release.zip](https://github.com/Dany-R/IBR.StringResourceBuilder2011/files/2094882/IBR.StringResourceBuilder2011_bak17_Release.zip)

**Comment by i18nuserz** [comment]
Thank you!!!  This one appears to be for VS 2010.  I have only VS 2012 and 2013 installed:(  The csproj upgrade succeeds but I get other errors eg:
A processor named 'VSPackageDesignerDirectiveProcessor' could not be found for the directive named 'VSPackageDesigner'. The transformation will not be run.  The following Exception was thrown:
System.IO.FileNotFoundException: Failed to resolve type for directive processor VSPackageDesignerDirectiveProcessor.
   at Microsoft.VisualStudio.TextTemplating.VSHost.TextTemplatingService.ResolveDirectiveProcessor(String processorName)

Do you happen to have a backup for VS 2012 or VS 2013??  Thank you!!

**Comment by i18nuserz** [comment]
Just wanted to update you... I upgraded to VS 2017 Community and after adding in the appropriate Visual.Studio.Shell references (for 14), I now able to build your app and am now trying it.  Thank you!!

**Comment by Dany-R** [comment]
Sorry for the late response.
I'm glad you solved it. I never had VS2013 and was using only Vs2010+2015 before.
Good luck with it and feel free to ask if you have questions. I'll try to answer them as good as I can ;)
Cheers, Dany
