### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by anders-eriksson** [Dany-R/IBR.StringResourceBuilder2011#7]
The new string interpolation is not recognized as strings

E.g. var foo = $"The number is: {number}";

This will not show up in the list of texts

**Comment by anders-eriksson** [comment]
I have discovered that it's useful that string interpolation isn't recognized!
I don't want to make log strings into resource.

So I close this!!

**Comment by Dany-R** [comment]
Ok, thank you.
Interpolated strings would otherwise have to be changed to `string.Format(...)` to be able to store the string in a resource file. I'll leave that up to the compiler (which is actually what it does) 😉
