### ISSUE TITLE
Question: Using resx file from a different project in the same solution?

### ISSUE THREAD

**Issue by boris-df** [Dany-R/IBR.StringResourceBuilder2011#8]
I'm writing Apps with Xamarin, so i have 3 projects in a solution as default (the forms code with all my UI and one for each plattform iOS and Android)

Also i have a project which is the Data-Project (holding classes and ressources i can then use in the Forms-Project (UI) and in the Plattform-Projects if needed (for custom renderers and such)

Now i like to hold all my string-ressources inside the Data-Project.

Is there a way to configure StringResourceBuilder to use the resx-file inside the Data-Project instead of the Forms-Project (where i select strings to create a string-resource from)?

**Comment by Dany-R** [comment]
There are no plans to have such a feature.
Sorry for the late reply.

**Comment by boris-df** [comment]
:D that was so late that i almost forgot about that question ;) 
No Problem - now i know that i didn't miss some setting or hidden trick to do that. Thanks for the answer :) 
And as there are not plans, i close this one :)
